import { FormControl, FormGroup } from '@angular/forms';

export type AutogeneratedProperties = 'id' | 'joinCode';
export type OmitAutogeneratedProperties<T> = Omit<T, AutogeneratedProperties>;
export type ToFormGroup<T> = FormGroup<{
  [K in keyof T]: FormControl<T[K] | null>;
}>;

export interface GameModel {
  id: string;
  name: string;
  turnLength: number;
  turnLengthUnits: TimeUnits;
  joinCode?: string;
}

export interface PlayerModel {
  id: string;
  name: string;
  color: string;
}

export enum TimeUnits {
  Seconds = 's',
  Minutes = 'min',
}

export enum LocalStorageKeys {
  NewGameForm = 'newGameForm',
  Players = 'players',
  Game = 'game',
}

export enum Endpoints {
  GAME = 'game',
  PLAYER = 'player',
}

export enum GameTypes {
  Local = 'local',
  Online = 'online',
}

export interface PlayerFormViewModel {
  name: string;
  color: string;
}

export interface GameFormViewModel {
  name: string;
  turnLength: number;
  turnLengthUnits: TimeUnits;
  gameType: GameTypes;
}
